<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_intelliplan_jobs"
 *
 * Auto generated by Extension Builder 2018-07-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Intelliplan jobs integration',
    'description' => 'Intelliplan jobs integration',
    'category' => 'plugin',
    'author' => 'Andrii Oprysko',
    'author_email' => 'andriy.oprysko@resultify.se',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.3',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
